name: Deploy to EC2

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AWS_INSTANCE_IP }} >> ~/.ssh/known_hosts

    # - name: Install PHP and dependencies
    #   run: sudo apt-get update && sudo apt-get install php php-mbstring php-xml

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Deploy to EC2
      run: "ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_INSTANCE_IP }} 'cd /var/www/ec2instance && git reset --hard && git pull origin main && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan config:clear && php artisan route:clear'"

    - name: Clear SSH key
      run: rm ~/.ssh/id_rsa